Fix Gigapipe Features
odigos-io/odigos pull request #2075
Opened 2024-12-25 12:04 UTC by lmangani

Gigapipe supports Logs, Metrics, Traces and Profiling. Updating the readme to reflect this correctly. Happy Holidays!

2024-12-26 09:38 UTC, BenElferink requested changes
Thank you @lmangani 😃
Can you please make the change in `docs/backends-overview.mdx` as well?

2024-12-26 10:30 UTC, lmangani commented
Hi Ben

What should we change exactly? We also provided your team w/ details for validation but never got feedback.

> signals:
>  - TRACES
>  - METRICS
>  - LOGS

2024-12-26 17:18 UTC, BenElferink commented
> Hi Ben
> 
> What should we change exactly? We also provided your team w/ details for validation
> 
> > signals:
> > 
> > * TRACES
> > * METRICS
> > * LOGS

The table in [docs/backends-overview.mdx](https://github.com/odigos-io/odigos/blob/264582d16d5826827453fe3666d76eb20c995527/docs/backends-overview.mdx?plain=1#L20), just apply the same change you did to `README.md`, that's all :)

2025-01-18 12:33 UTC, BenElferink approved these changes

2025-01-18 13:18 UTC, merged